export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const INPROGRESS = 'INPROGRESS';

//PROFILE *TUTORIAL
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

//SIDEBAR
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

//ITEM
export const GET_COUNT = 'GET_COUNT';
export const GET_COUNT_FAIL = 'GET_COUNT_FAIL';
export const GET_ITEM = 'GET_ITEM';
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';
export const GET_DRAFT_COUNT = 'GET_DRAFT_COUNT';
export const GET_DRAFT_COUNT_FAIL = 'GET_DRAFT_COUNT_FAIL';
export const GET_DRAFT = 'GET_DRAFT';
export const GET_DRAFT_FAIL = 'GET_DRAFT_FAIL';

//ADD ITEM
export const ADD_PRODUCTINFO = 'ADD_PRODUCTINFO';
export const ADD_PRODUCTDESC = 'ADD_PRODUCTDESC';
export const ADD_PRODUCTDETAIL = 'ADD_PRODUCTDETAIL';
export const ADD_PRODUCTFAIL = 'ADD_PRODUCTFAIL';
export const ADD_PRODUCTSUCCESS = 'ADD_SUCCESS';
export const ADD_PROD_IMG_FAIL = 'ADD_PRODUCT_IMG_FAIL';
export const ADD_PROD_IMG_SUCCESS = 'ADD_PROD_IMG_SUCCESS';
export const ADD_PROD_EXTRA_IMG_FAIL = 'ADD_PROD_EXTRA_IMG_FAIL';
export const ADD_PROD_EXTRA_IMG_SUCCESS = 'ADD_PROD_EXTRA_IMG_SUCCESS';

//ADD EMPLOYEE
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';

//EMPLOYEE
export const GET_EMPLOYEE_COUNT = 'GET_EMPLOYEE_COUNT';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_COUNT_FAIL = 'GET_EMPLOYEE_COUNT_FAIL';
export const GET_EMPLOYEE_FAIL = 'GET_EMPLOYEE_FAIL';

//ORDER
export const GET_ORDER_COUNT = 'GET_ORDER_COUNT';
export const GET_ORDER_COUNT_FAIL = 'GET_ORDER_COUNT_FAIL';
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const GET_TO_DELIVER_COUNT = 'GET_TO_DELIVER_COUNT';
export const GET_TO_DELIVER_COUNT_FAIL = 'GET_TO_DELIVER_COUNT_FAIL';
export const GET_TO_DELIVER = 'GET_TO_DELIVER'
export const GET_TO_DELIVER_FAIL = 'GET_TO_DELIVER_FAIL'


export const GET_TO_PACK_COUNT = 'GET_TO_PACK_COUNT';
export const GET_TO_PACK_COUNT_FAIL = 'GET_TO_PACK_COUNT_FAIL';
export const GET_TO_PACK = 'GET_TO_PACK'
export const GET_TO_PACK_FAIL = 'GET_TO_PACK_FAIL'

//SEARCH PRODUCT

export const GET_PRODUCT_SEARCH = 'PRODUCT_SEARCH';
export const GET_PRODUCT_SEARCH_FAIL = 'GET_ORDER_COUNT_FAIL';